import { useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, HandCoins, Pencil, Trash2, UserRound } from 'lucide-react'
import { Button, Field, Input, Modal, Select, Textarea } from '../../components/ui'
import { TypedConfirmModal } from '../../components/business/TypedConfirmModal'
import { useToast } from '../../components/Toast'
import { useBusiness } from '../../lib/business/store'
import { businessMoney, todayBusinessISO } from '../../lib/business/finance'
import type { BusinessDayClosing } from '../../lib/business/types'

const DENOMINATIONS=[500,200,100,50,20,10,5,2,1]

export default function BusinessDayClose(){
 const {data,canWrite,canAdmin,closeDay,editDayClose,deleteDayClose}=useBusiness()
 const toast=useToast()
 const allCash=data.accountBalances.filter(a=>a.kind==='cash')
 const brokenCash=allCash.filter(a=>Number(a.balance)<0)
 const cash=allCash.filter(a=>Number(a.balance)>=0)
 const [target,setTarget]=useState<string|null>(null),[counts,setCounts]=useState<Record<string,string>>({}),[otherCash,setOtherCash]=useState(''),[differenceReason,setDifferenceReason]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false)
 const [editing,setEditing]=useState<BusinessDayClosing|null>(null),[deleting,setDeleting]=useState<BusinessDayClosing|null>(null),[confirmEdit,setConfirmEdit]=useState(false),[confirmDelete,setConfirmDelete]=useState(false)
 const [editAccountId,setEditAccountId]=useState(''),[editDate,setEditDate]=useState(''),[editExpected,setEditExpected]=useState(''),[editCounted,setEditCounted]=useState(''),[editNote,setEditNote]=useState('')
 const targetBalance=cash.find(a=>a.account_id===target)?.balance??0
 const counted=useMemo(()=>DENOMINATIONS.reduce((sum,v)=>sum+v*(Number(counts[String(v)])||0),0)+(Number(otherCash)||0),[counts,otherCash])
 const difference=counted-Number(targetBalance),today=todayBusinessISO()
 const holderFor=(id:string)=>{const a=data.accounts.find(x=>x.id===id);return a?.custodian_partner_id?data.partners.find(p=>p.id===a.custodian_partner_id)?.name??null:null}
 const close=async()=>{if(!target)return;setBusy(true);try{const reason=Math.abs(difference)>0.005&&differenceReason?'['+differenceReason+'] ':'';await closeDay(target,counted,(reason+note.trim()).trim());toast.success('Cash location closed for today');setTarget(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not close cash location')}finally{setBusy(false)}}
 const openEdit=(c:BusinessDayClosing)=>{setEditing(c);setEditAccountId(c.account_id);setEditDate(c.close_date);setEditExpected(String(c.expected_balance));setEditCounted(String(c.counted_balance));setEditNote(c.note??'')}
 const saveEdit=async()=>{if(!editing||!editAccountId||!editDate)return;setBusy(true);try{await editDayClose(editing.id,{accountId:editAccountId,closeDate:editDate,expectedBalance:Number(editExpected)||0,countedBalance:Number(editCounted)||0,note:editNote});toast.success('Day closing updated');setConfirmEdit(false);setEditing(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not update day closing')}finally{setBusy(false)}}
 const remove=async()=>{if(!deleting)return;setBusy(true);try{await deleteDayClose(deleting.id);toast.success('Day closing deleted');setConfirmDelete(false);setDeleting(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not delete day closing')}finally{setBusy(false)}}
 return <div className="space-y-3 min-w-0">
  <div><h1 className="text-[17px] font-bold text-navy-900">Count cash</h1><p className="text-[11.5px] text-navy-400">Count the cash physically present and compare it with what Prangan expects.</p></div>
  <div className="rounded-xl bg-navy-50 border border-navy-100 px-3 py-2 flex gap-2 text-[11px] text-navy-600"><HandCoins size={15} className="shrink-0 mt-0.5"/><span>If cash was handed to a partner or staff member, record that first. Use this page only to check how much cash is physically there.</span></div>
  {brokenCash.length>0&&<div className="rounded-xl border border-red-200 bg-red-50 overflow-hidden">
   <div className="px-3 py-2.5 flex gap-2.5"><AlertTriangle size={16} className="text-over shrink-0 mt-0.5"/><div><div className="text-[12px] font-bold text-navy-900">Fix the cash record before counting it</div><div className="text-[10.5px] leading-relaxed text-navy-500">Prangan sees payments from this cash before enough cash was recorded. This is a record problem, not physical negative cash.</div></div></div>
   {brokenCash.map(account=><div key={account.account_id} className="border-t border-red-100 px-3 py-2 flex items-center gap-2"><div className="flex-1"><div className="text-[11.5px] font-semibold text-navy-800">{account.name}</div><div className="text-[9.5px] text-navy-400">Money source missing</div></div><div className="num text-[12px] font-bold text-over">{businessMoney(Math.abs(Number(account.balance)))}</div></div>)}
  </div>
  {cash.map(account=>{const closing=data.closings.find(c=>c.account_id===account.account_id&&c.close_date===today),holder=holderFor(account.account_id);return <div key={account.account_id} className="rounded-xl border border-cream-200 bg-white p-3">
   <div className="flex items-center justify-between gap-2"><div className="min-w-0"><div className="flex items-center gap-1.5"><div className="text-[12px] font-bold text-navy-800 truncate">{account.name}</div>{holder&&<span className="inline-flex items-center gap-1 rounded-full bg-saffron-50 border border-saffron-200 px-2 py-0.5 text-[9px] font-bold text-saffron-700"><UserRound size={10}/> WITH {holder.toUpperCase()}</span>}</div><div className="text-[10.5px] text-navy-400">Expected right now</div></div><div className="num text-[18px] font-bold">{businessMoney(account.balance)}</div></div>
   {closing?<div className={'mt-2 rounded-xl border px-3 py-2 flex items-center gap-2 '+(Number(closing.difference)===0?'bg-green-50 border-green-100':'bg-red-50 border-red-100')}><CheckCircle2 size={15} className={Number(closing.difference)===0?'text-paid':'text-over'}/><div className="flex-1 min-w-0"><div className="text-[11px] font-semibold text-navy-700">Closed · counted {businessMoney(closing.counted_balance)}</div><div className="text-[10px] text-navy-400 truncate">{Number(closing.difference)===0?'Matched':(Number(closing.difference)<0?'Short ':'Over ')+businessMoney(Math.abs(Number(closing.difference)))}</div></div>{canAdmin&&<button onClick={()=>openEdit(closing)} className="h-8 w-8 rounded-lg bg-white text-navy-500 flex items-center justify-center"><Pencil size={13}/></button>}</div>:canWrite?<Button full variant="soft" className="mt-2 !min-h-[38px] !text-[12px]" onClick={()=>{setTarget(account.account_id);setCounts({});setOtherCash('');setDifferenceReason('');setNote('')}}>Count this cash</Button>:null}
  </div>})}
  {cash.length===0&&brokenCash.length===0&&<div className="rounded-xl border border-cream-200 bg-white px-4 py-7 text-center text-[12px] text-navy-400">No cash places yet. Add Shop Cash or Cash with a partner under Cash, bank & UPI first.</div>}
  <section><h2 className="text-[13px] font-bold text-navy-900 mb-1.5">Recent cash counts</h2><div className="rounded-xl border border-cream-200 bg-white overflow-hidden">{data.closings.slice(0,15).map(c=>{const holder=holderFor(c.account_id);return <div key={c.id} className="px-3 py-2.5 border-b border-cream-100 last:border-0 flex items-center gap-2 min-w-0"><div className="flex-1 min-w-0"><div className="text-[11.5px] font-semibold truncate">{data.accounts.find(a=>a.id===c.account_id)?.name||'Cash'}{holder?' · with '+holder:''} · {new Date(c.close_date+'T00:00:00').toLocaleDateString('en-IN')}</div><div className="text-[10px] text-navy-400 truncate">Expected {businessMoney(c.expected_balance)} · Counted {businessMoney(c.counted_balance)}</div></div><div className={'num text-[11.5px] font-bold '+(Number(c.difference)===0?'text-paid':'text-over')}>{businessMoney(c.difference)}</div>{canAdmin&&<><button onClick={()=>openEdit(c)} className="h-8 w-8 shrink-0 rounded-lg bg-navy-50 text-navy-600 flex items-center justify-center"><Pencil size={13}/></button><button onClick={()=>{setDeleting(c);setConfirmDelete(true)}} className="h-8 w-8 shrink-0 rounded-lg bg-red-50 text-over flex items-center justify-center"><Trash2 size={13}/></button></>}</div>})}</div></section>
  <Modal open={!!target} onClose={()=>{if(!busy)setTarget(null)}} title="Count actual cash" wide>
   {target&&<div className="rounded-xl bg-navy-50 border border-navy-100 px-3 py-2"><div className="flex items-center justify-between"><span className="text-[11px] font-semibold text-navy-500">{cash.find(a=>a.account_id===target)?.name}</span><span className="num text-[17px] font-bold text-navy-900">{businessMoney(targetBalance)}</span></div>{holderFor(target)&&<div className="text-[9.5px] text-saffron-700 mt-0.5">Expected business cash currently with {holderFor(target)}</div>}</div>}
   <div className="rounded-xl border border-cream-200 bg-white overflow-hidden">{DENOMINATIONS.map(v=>{const count=Number(counts[String(v)])||0;return <div key={v} className="grid grid-cols-[52px_minmax(0,1fr)_82px] items-center gap-2 px-3 py-2 border-b border-cream-100 last:border-0"><div className="num text-[13px] font-bold">₹{v}</div><Input inputMode="numeric" value={counts[String(v)]??''} onChange={e=>setCounts(c=>({...c,[String(v)]:e.target.value.replace(/[^0-9]/g,'')}))} placeholder="0" className="!min-h-[36px]"/><div className="num text-right text-[11px] font-semibold">{businessMoney(v*count)}</div></div>})}</div>
   <Field label="Other cash / coins"><Input inputMode="decimal" value={otherCash} onChange={e=>setOtherCash(e.target.value)} placeholder="0"/></Field>
   <div className={'rounded-xl border px-3 py-3 '+(Math.abs(difference)<0.005?'bg-green-50 border-green-100':'bg-red-50 border-red-100')}><div className="flex justify-between"><span className="text-[11px]">Counted</span><span className="num font-bold">{businessMoney(counted)}</span></div><div className="flex justify-between mt-1"><span className="text-[11px]">Difference</span><span className="num font-bold">{Math.abs(difference)<0.005?'Matched':(difference<0?'Short ':'Over ')+businessMoney(Math.abs(difference))}</span></div></div>
   {Math.abs(difference)>0.005&&<Field label="Why is there a difference?" hint="If money really moved, add the missing money entry after this check so tomorrow starts correctly."><Select value={differenceReason} onChange={e=>setDifferenceReason(e.target.value)}><option value="">Choose reason</option><option>Missed cash expense</option><option>Unrecorded cash received</option><option>Unrecorded handover to partner</option><option>Unrecorded handover to staff</option><option>Personal withdrawal not entered</option><option>Counting difference</option><option>Other</option></Select></Field>}
   <Field label="Note"><Textarea value={note} onChange={e=>setNote(e.target.value)}/></Field><Button full loading={busy} disabled={Math.abs(difference)>0.005&&!differenceReason} onClick={close}>Save cash count</Button>
  </Modal>
  <Modal open={!!editing} onClose={()=>{if(!busy)setEditing(null)}} title="Edit day closing"><Field label="Cash location"><Select value={editAccountId} onChange={e=>setEditAccountId(e.target.value)}>{cash.map(a=><option key={a.account_id} value={a.account_id}>{a.name}{holderFor(a.account_id)?' · with '+holderFor(a.account_id):''}</option>)}</Select></Field><Field label="Close date"><Input type="date" value={editDate} onChange={e=>setEditDate(e.target.value)}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Expected"><Input inputMode="decimal" value={editExpected} onChange={e=>setEditExpected(e.target.value)}/></Field><Field label="Counted"><Input inputMode="decimal" value={editCounted} onChange={e=>setEditCounted(e.target.value)}/></Field></div><Field label="Note"><Textarea value={editNote} onChange={e=>setEditNote(e.target.value)}/></Field><Button full onClick={()=>setConfirmEdit(true)}>Review edit</Button></Modal>
  <TypedConfirmModal open={confirmEdit} mode="EDIT" title="Confirm day-close edit" body="This directly replaces the selected closing values with the fields you entered." busy={busy} onClose={()=>setConfirmEdit(false)} onConfirm={saveEdit}/>
  <TypedConfirmModal open={confirmDelete} mode="DELETE" title="Delete day closing" body="This permanently deletes this day-closing record. Type DELETE to continue." busy={busy} onClose={()=>{setConfirmDelete(false);setDeleting(null)}} onConfirm={remove}/>
 </div>
}
