import { useMemo, useState } from 'react'
import { Download, ExternalLink, HandCoins, Paperclip, Pencil, RefreshCw, Search, Trash2, Upload, WalletCards } from 'lucide-react'
import { useOutletContext } from 'react-router-dom'
import { Badge, Button, Field, Input, Modal, Select, Textarea } from '../../components/ui'
import { TypedConfirmModal } from '../../components/business/TypedConfirmModal'
import { useToast } from '../../components/Toast'
import { useBusiness } from '../../lib/business/store'
import { getBusinessProofUrl } from '../../lib/business/data'
import { accountAvailable, businessMoney, businessTransactionLabels, expensePaidByLabel, transactionCashDirection, transactionRemaining } from '../../lib/business/finance'
import { exportCsv } from '../../lib/csv'
import type { BusinessOutletContext } from '../../components/business/BusinessLayout'
import type { SerializableTransactionInput } from '../../lib/business/preferences'
import type { BusinessPaidBy, BusinessTransaction } from '../../lib/business/types'

const filters=['all','to collect','to pay','income','expense','partner','review'] as const

export default function BusinessLedger(){
 const {data,canWrite,deleteTransaction,editTransactionDetails,attachProof,settleTransaction}=useBusiness()
 const {openTransaction}=useOutletContext<BusinessOutletContext>()
 const toast=useToast()
 const [filter,setFilter]=useState<typeof filters[number]>('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<BusinessTransaction|null>(null)
 const [settleOpen,setSettleOpen]=useState(false),[settleAmount,setSettleAmount]=useState(''),[settlePaidBy,setSettlePaidBy]=useState<BusinessPaidBy>('business'),[settleAccountId,setSettleAccountId]=useState(''),[settlePartnerId,setSettlePartnerId]=useState(''),[settleNote,setSettleNote]=useState('')
 const [editOpen,setEditOpen]=useState(false),[editCounterparty,setEditCounterparty]=useState(''),[editCategoryId,setEditCategoryId]=useState(''),[editDueDate,setEditDueDate]=useState(''),[editNote,setEditNote]=useState('')
 const [confirmDelete,setConfirmDelete]=useState(false),[saving,setSaving]=useState(false),[proofUploading,setProofUploading]=useState(false)

 const paymentsFor=(id:string)=>data.transactionPayments.filter(p=>p.transaction_id===id)
 const settleAvailable=accountAvailable(settleAccountId,data.accountBalances)
 const settleTooHigh=!!selected&&selected.kind==='expense'&&settlePaidBy==='business'&&!!settleAccountId&&Number(settleAmount)>settleAvailable
 const list=useMemo(()=>{const q=query.trim().toLowerCase();return data.transactions.filter(tx=>{
  if(tx.kind==='reversal'||tx.reversed_at)return false
  if(filter==='income'&&!['income','refund'].includes(tx.kind))return false
  if(filter==='expense'&&!['expense','personal_expense','reimbursement'].includes(tx.kind))return false
  if(filter==='to collect'&&!(tx.kind==='income'&&tx.payment_status!=='paid'))return false
  if(filter==='to pay'&&!(tx.kind==='expense'&&tx.payment_status!=='paid'))return false
  if(filter==='partner'&&!['partner_capital','partner_advance','personal_expense','reimbursement','withdrawal'].includes(tx.kind)&&!(tx.kind==='expense'&&data.transactionPayments.some(p=>p.transaction_id===tx.id&&!!p.partner_id)))return false
  if(filter==='review'&&tx.approval_status!=='pending')return false
  if(!q)return true
  const partner=data.partners.find(p=>p.id===tx.partner_id)?.name??'',category=data.categories.find(c=>c.id===tx.category_id)?.name??'',payer=expensePaidByLabel(tx,data.accounts,data.partners,data.transactionPayments)??''
  return [tx.amount,tx.counterparty,tx.note,partner,category,payer,tx.payment_status,tx.approval_status,businessTransactionLabels[tx.kind]].some(v=>String(v??'').toLowerCase().includes(q))
 })},[data.transactions,data.transactionPayments,data.partners,data.categories,data.accounts,filter,query])

 const download=()=>exportCsv('business-ledger.csv',['Date','Type','Amount','Paid / collected','Remaining','Payment','Paid by','From','To','Partner','Category','Review','Party','Note'],list.map(tx=>[
  new Date(tx.occurred_at).toLocaleString('en-IN'),businessTransactionLabels[tx.kind],Number(tx.amount),['income','expense'].includes(tx.kind)?Number(tx.paid_amount??0):'', ['income','expense'].includes(tx.kind)?transactionRemaining(tx):'', ['income','expense'].includes(tx.kind)?tx.payment_status:'',tx.kind==='expense'?expensePaidByLabel(tx,data.accounts,data.partners,data.transactionPayments)??'':'',data.accounts.find(a=>a.id===tx.account_id)?.name,data.accounts.find(a=>a.id===tx.to_account_id)?.name,data.partners.find(p=>p.id===tx.partner_id)?.name,data.categories.find(c=>c.id===tx.category_id)?.name,tx.approval_status,tx.counterparty??'',tx.note??''
 ]))

 const openSettlement=()=>{if(!selected||!['income','expense'].includes(selected.kind)||transactionRemaining(selected)<=0)return;setSettleAmount(String(transactionRemaining(selected)));setSettlePaidBy('business');setSettleAccountId(data.accounts.find(a=>a.active)?.id??'');setSettlePartnerId(data.partners.find(p=>p.active)?.id??'');setSettleNote('');setSettleOpen(true)}
 const settle=async()=>{if(!selected)return;const amount=Number(settleAmount);if(amount<=0||amount>transactionRemaining(selected)||settleTooHigh)return;if(selected.kind==='income'&&!settleAccountId)return;if(selected.kind==='expense'&&settlePaidBy==='business'&&!settleAccountId)return;if(selected.kind==='expense'&&settlePaidBy==='partner'&&!settlePartnerId)return;setSaving(true);try{await settleTransaction(selected.id,{amount,accountId:selected.kind==='income'||settlePaidBy==='business'?settleAccountId:null,partnerId:selected.kind==='expense'&&settlePaidBy==='partner'?settlePartnerId:null,note:settleNote});toast.success(selected.kind==='income'?'Collection recorded':'Payment recorded');setSettleOpen(false);setSelected(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not record settlement')}finally{setSaving(false)}}
 const openDetailsEdit=()=>{if(!selected)return;setEditCounterparty(selected.counterparty??'');setEditCategoryId(selected.category_id??'');setEditDueDate(selected.due_date??'');setEditNote(selected.note??'');setEditOpen(true)}
 const saveDetails=async()=>{if(!selected)return;setSaving(true);try{await editTransactionDetails(selected.id,{counterparty:editCounterparty,categoryId:editCategoryId||null,dueDate:editDueDate||null,note:editNote});toast.success('Transaction details updated');setEditOpen(false);setSelected(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not update details')}finally{setSaving(false)}}
 const removeTransaction=async()=>{if(!selected)return;setSaving(true);try{await deleteTransaction(selected.id);toast.success('Transaction permanently deleted');setConfirmDelete(false);setSelected(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not delete transaction')}finally{setSaving(false)}}
 const repeatSelected=()=>{if(!selected||selected.kind==='reversal')return;const preset=transactionPreset(selected,paymentsFor(selected.id));setSelected(null);openTransaction(preset.kind as Exclude<BusinessTransaction['kind'],'reversal'|'personal_expense'>,preset)}
 const viewProof=async()=>{if(!selected)return;const a=data.attachments.find(x=>x.transaction_id===selected.id);if(!a)return;const url=await getBusinessProofUrl(a.storage_path);if(!url){toast.error('Could not open this proof.');return}window.open(url,'_blank','noopener,noreferrer')}
 const addProof=async(file:File|null)=>{if(!file||!selected)return;setProofUploading(true);try{await attachProof(selected.id,file);toast.success('Proof attached')}catch(error){toast.error(error instanceof Error?error.message:'Could not attach proof')}finally{setProofUploading(false)}}

 return <div className="space-y-2.5 min-w-0">
  <div><h1 className="text-[17px] font-bold text-navy-900">Money entries</h1><p className="text-[11.5px] text-navy-400">A simple history of money received, expenses, amounts still to collect/pay, and partner money.</p></div>
  <div className="rounded-xl bg-navy-50 border border-navy-100 px-3 py-2 text-[11px] leading-relaxed text-navy-600"><strong>To collect</strong> means someone still owes the business. <strong>To pay</strong> means the business still owes a vendor. “Partner paid personally” means the business owes that partner back.</div>
  <div className="flex items-center gap-2 min-w-0"><div className="relative flex-1 min-w-0"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-navy-300"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search amount, party, note…" className="!min-h-[40px] !text-[13px] !pl-9"/></div><button onClick={download} aria-label="Export ledger CSV" className="h-10 w-10 shrink-0 rounded-xl border border-cream-300 bg-white flex items-center justify-center text-navy-600"><Download size={16}/></button></div>
  <div className="dense-scroll flex gap-1.5 overflow-x-auto pb-0.5 max-w-full">{filters.map(item=><button key={item} onClick={()=>setFilter(item)} className={'shrink-0 rounded-full border px-3 min-h-[34px] text-[11px] font-semibold capitalize '+(filter===item?'bg-navy-900 border-navy-900 text-white':'bg-white border-cream-300 text-navy-500')}>{item}</button>)}</div>
  <div className="rounded-xl border border-cream-200 bg-white overflow-hidden min-w-0">{list.length===0?<div className="px-4 py-8 text-center text-[12.5px] text-navy-400">No matching transactions.</div>:list.map(tx=>{const direction=transactionCashDirection(tx),proof=data.attachments.some(a=>a.transaction_id===tx.id),remaining=transactionRemaining(tx),payer=expensePaidByLabel(tx,data.accounts,data.partners,data.transactionPayments),open=['income','expense'].includes(tx.kind)&&remaining>0;return <button key={tx.id} onClick={()=>setSelected(tx)} className="w-full min-w-0 min-h-[58px] flex items-center gap-2 px-3 py-2 border-b border-cream-100 last:border-0 text-left active:bg-cream-50"><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5 flex-wrap min-w-0"><span className="text-[12.5px] font-semibold text-navy-800 truncate">{businessTransactionLabels[tx.kind]}</span>{proof&&<Paperclip size={11} className="text-navy-300 shrink-0"/>}{['income','expense'].includes(tx.kind)&&<PaymentBadge tx={tx}/>} {tx.approval_status==='pending'&&<Badge tone="amber">REVIEW</Badge>}</div><div className="text-[10.5px] text-navy-400 truncate">{tx.counterparty||payer||data.accounts.find(a=>a.id===tx.account_id)?.name||'Business'} · {new Date(tx.occurred_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}{open?' · '+businessMoney(remaining)+' left':''}</div></div><div className={'num shrink-0 text-[13px] font-bold whitespace-nowrap '+(open?'text-pend':direction==='in'?'text-paid':direction==='out'?'text-over':'text-navy-700')}>{open?businessMoney(tx.amount):(direction==='in'?'+':direction==='out'?'-':'')+businessMoney(tx.amount)}</div></button>})}</div>
  <Button full variant="soft" onClick={()=>openTransaction('expense')}>Add money entry</Button>

  <Modal open={!!selected} onClose={()=>{if(!saving&&!proofUploading)setSelected(null)}} title="Transaction details" wide>
   {selected&&(()=>{const txPayments=paymentsFor(selected.id),remaining=transactionRemaining(selected),open=['income','expense'].includes(selected.kind)&&remaining>0;return <>
    <div className="flex items-start justify-between gap-3 min-w-0"><div className="min-w-0"><div className="font-bold text-navy-900 truncate">{businessTransactionLabels[selected.kind]}</div><div className="text-[11px] text-navy-400">{new Date(selected.occurred_at).toLocaleString('en-IN')}</div></div><div className="num shrink-0 text-[20px] font-bold">{businessMoney(selected.amount)}</div></div>
    {['income','expense'].includes(selected.kind)&&<div className="grid grid-cols-3 gap-1.5"><MoneyInfo label="Total" value={selected.amount}/><MoneyInfo label={selected.kind==='income'?'Collected':'Paid'} value={selected.paid_amount??0} tone="green"/><MoneyInfo label="Remaining" value={remaining} tone={remaining>0?'amber':'green'}/></div>}
    <div className="grid grid-cols-2 gap-2 text-[12px]"><Info label="Payment" value={['income','expense'].includes(selected.kind)?selected.payment_status:'Paid'}/><Info label="Review" value={selected.approval_status.replace('_',' ')}/><Info label="Party" value={selected.counterparty||'—'}/><Info label="Category" value={data.categories.find(c=>c.id===selected.category_id)?.name||'—'}/></div>
    {open&&canWrite&&<Button full variant="accent" onClick={openSettlement}>{selected.kind==='income'?<WalletCards size={14}/>:<HandCoins size={14}/>} {selected.kind==='income'?'Receive payment':'Pay / settle expense'}</Button>}
    {txPayments.length>0&&<section><div className="text-[10px] font-bold tracking-wide text-navy-400 mb-1">PAYMENT HISTORY</div><div className="rounded-xl border border-cream-200 bg-white overflow-hidden">{txPayments.map(p=>{const source=p.account_id?data.accounts.find(a=>a.id===p.account_id)?.name||'Business account':data.partners.find(x=>x.id===p.partner_id)?.name||'Partner';return <div key={p.id} className="px-3 py-2 flex items-center gap-2 border-b border-cream-100 last:border-0"><div className="min-w-0 flex-1"><div className="text-[11.5px] font-semibold text-navy-700 truncate">{source}</div><div className="text-[9.5px] text-navy-400">{new Date(p.occurred_at).toLocaleDateString('en-IN')}{p.note?' · '+p.note:''}</div></div><div className="num text-[12px] font-bold">{businessMoney(p.amount)}</div></div>})}</div></section>}
    {(selected.note||selected.due_date)&&<div className="rounded-xl bg-cream-100 px-3 py-2 text-[11.5px] text-navy-600 break-words">{selected.due_date&&<div className="font-semibold">Due {new Date(selected.due_date+'T00:00:00').toLocaleDateString('en-IN')}</div>}{selected.note&&<div>{selected.note}</div>}</div>}
    {data.attachments.some(a=>a.transaction_id===selected.id)?<Button full variant="soft" onClick={()=>void viewProof()}><ExternalLink size={14}/> View proof</Button>:canWrite&&['expense','refund'].includes(selected.kind)?<label className="min-h-[42px] rounded-xl border border-dashed border-saffron-300 bg-saffron-50 px-3 flex items-center justify-center gap-2 cursor-pointer text-[11.5px] font-bold text-saffron-800"><Upload size={14}/>{proofUploading?'Uploading…':'Add proof'}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" className="sr-only" disabled={proofUploading} onChange={e=>void addProof(e.target.files?.[0]??null)}/></label>:null}
    {selected.kind!=='reversal'&&<Button full variant="soft" onClick={repeatSelected}><RefreshCw size={14}/> Repeat this transaction</Button>}
    {canWrite&&selected.kind!=='reversal'&&<><div className="grid grid-cols-2 gap-2"><Button variant="soft" onClick={openDetailsEdit}><Pencil size={14}/> Edit details</Button><Button variant="danger" onClick={()=>setConfirmDelete(true)}><Trash2 size={14}/> Delete</Button></div>{txPayments.length>0&&<p className="text-[10px] text-navy-400 text-center">Amount/payment sources are locked once money has moved. Delete and re-enter to replace the financial record; party, category, due date and notes remain editable.</p>}</>}
   </>})()}
  </Modal>

  <Modal open={settleOpen} onClose={()=>{if(!saving)setSettleOpen(false)}} title={selected?.kind==='income'?'Receive customer payment':'Pay open expense'}>
   {selected&&<><div className="rounded-xl bg-navy-50 border border-navy-100 px-3 py-2 flex items-center justify-between"><span className="text-[11px] text-navy-500">Remaining</span><span className="num text-[16px] font-bold">{businessMoney(transactionRemaining(selected))}</span></div><Field label="Amount"><Input inputMode="decimal" value={settleAmount} onChange={e=>setSettleAmount(e.target.value)} autoFocus/></Field>
   {selected.kind==='expense'&&<Field label="Who pays this part?"><Select value={settlePaidBy} onChange={e=>setSettlePaidBy(e.target.value as BusinessPaidBy)}><option value="business">Business money</option><option value="partner">Partner personally</option></Select></Field>}
   {(selected.kind==='income'||settlePaidBy==='business')&&<Field label={selected.kind==='income'?'Money received into':'Pay from'} hint={selected.kind==='expense'&&settlePaidBy==='business'&&settleAccountId?'Available here: '+businessMoney(settleAvailable):undefined}><Select value={settleAccountId} onChange={e=>setSettleAccountId(e.target.value)}><option value="">Choose cash / bank / UPI</option>{data.accounts.filter(a=>a.active).map(a=>{const h=a.custodian_partner_id?data.partners.find(p=>p.id===a.custodian_partner_id)?.name:null;const bal=data.accountBalances.find(b=>b.account_id===a.id)?.balance??0;return <option key={a.id} value={a.id}>{a.name}{h?' · with '+h:''} · {businessMoney(bal)}</option>})}</Select></Field>}
   {selected.kind==='expense'&&settlePaidBy==='partner'&&<Field label="Partner who paid personally" hint="The business will owe this partner back."><Select value={settlePartnerId} onChange={e=>setSettlePartnerId(e.target.value)}><option value="">Choose partner</option>{data.partners.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field>}
   {settleTooHigh&&<div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-[11px] leading-relaxed text-navy-600"><strong>Not enough recorded money here.</strong> Available {businessMoney(settleAvailable)}. Record where the money came from, choose another money place, or choose Partner personally if that is what actually happened.</div>}
   <Field label="Payment note"><Textarea value={settleNote} onChange={e=>setSettleNote(e.target.value)} placeholder="Optional"/></Field><Button full loading={saving} disabled={Number(settleAmount)<=0||Number(settleAmount)>transactionRemaining(selected)||settleTooHigh} onClick={settle}>{selected.kind==='income'?'Record money received':'Record payment'}</Button></>}
  </Modal>

  <Modal open={editOpen} onClose={()=>{if(!saving)setEditOpen(false)}} title="Edit transaction details"><Field label="Customer / vendor / party"><Input value={editCounterparty} onChange={e=>setEditCounterparty(e.target.value)}/></Field><Field label="Category"><Select value={editCategoryId} onChange={e=>setEditCategoryId(e.target.value)}><option value="">No category</option>{data.categories.filter(c=>c.active||c.id===selected?.category_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field>{selected&&['income','expense'].includes(selected.kind)&&selected.payment_status!=='paid'&&<Field label={selected.kind==='income'?'Expected by':'Due date'}><Input type="date" value={editDueDate} onChange={e=>setEditDueDate(e.target.value)}/></Field>}<Field label="Note"><Textarea value={editNote} onChange={e=>setEditNote(e.target.value)}/></Field><Button full loading={saving} onClick={saveDetails}>Save details</Button></Modal>
  <TypedConfirmModal open={confirmDelete} mode="DELETE" title="Delete transaction permanently" body="This permanently deletes this transaction, its payment history, balance entries, reviews and proof record. Type DELETE to continue." busy={saving} onClose={()=>setConfirmDelete(false)} onConfirm={removeTransaction}/>
 </div>
}
function PaymentBadge({tx}:{tx:BusinessTransaction}){if(tx.payment_status==='paid')return <Badge tone="green">{tx.kind==='income'?'COLLECTED':'PAID'}</Badge>;if(tx.payment_status==='partial')return <Badge tone="amber">PARTIAL</Badge>;return <Badge tone="amber">{tx.kind==='income'?'TO COLLECT':'TO PAY'}</Badge>}
function MoneyInfo({label,value,tone='navy'}:{label:string;value:number;tone?:'navy'|'green'|'amber'}){const cls=tone==='green'?'text-paid':tone==='amber'?'text-pend':'text-navy-900';return <div className="rounded-lg bg-cream-100 px-2 py-2"><div className="text-[9.5px] text-navy-400">{label}</div><div className={'num text-[12px] font-bold '+cls}>{businessMoney(value)}</div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-cream-200 bg-white px-3 py-2 min-w-0"><div className="text-[10px] text-navy-400">{label}</div><div className="font-semibold text-navy-700 truncate capitalize">{value}</div></div>}
function transactionPreset(tx:BusinessTransaction,payments:Array<{account_id:string|null;partner_id:string|null}>):SerializableTransactionInput{const first=payments[0];if(tx.kind==='personal_expense')return{kind:'expense',amount:Number(tx.amount),partnerId:tx.partner_id,categoryId:tx.category_id,counterparty:tx.counterparty??'',note:tx.note??'',paymentStatus:'paid',paidBy:'partner'};return{kind:tx.kind as SerializableTransactionInput['kind'],amount:Number(tx.amount),accountId:first?.account_id??tx.account_id,toAccountId:tx.to_account_id,partnerId:first?.partner_id??tx.partner_id,categoryId:tx.category_id,counterparty:tx.counterparty??'',note:tx.note??'',paymentStatus:['income','expense'].includes(tx.kind)?(tx.payment_status==='unpaid'?'unpaid':'paid'):undefined,paidBy:tx.kind==='expense'&&tx.payment_status!=='unpaid'?((first?.partner_id??tx.partner_id)?'partner':'business'):undefined,dueDate:tx.due_date}}
