import { ArrowDownLeft, ArrowRight, ArrowUpRight, Building2, HandCoins, UserRound, UsersRound, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../../components/ui'
import { useBusiness } from '../../lib/business/store'
import { businessMoney, transactionRemaining } from '../../lib/business/finance'

export default function BusinessMoneyMap(){
 const {data}=useBusiness()
 const active=data.accountBalances.filter(b=>data.accounts.find(a=>a.id===b.account_id)?.active!==false)
 const staffHeld=data.staffPositions.reduce((sum,p)=>sum+Number(p.advance_balance),0)
 const total=active.reduce((sum,b)=>sum+Number(b.balance),0)+staffHeld
 const partnerHeld=active.filter(b=>!!data.accounts.find(a=>a.id===b.account_id)?.custodian_partner_id)
 const shared=active.filter(b=>!data.accounts.find(a=>a.id===b.account_id)?.custodian_partner_id)
 const partnerDue=data.partnerPositions.reduce((sum,p)=>sum+Number(p.outstanding_due),0)
 const staffDue=data.staffPositions.reduce((sum,p)=>sum+Number(p.outstanding_due),0)
 const receivables=data.transactions.filter(tx=>tx.kind==='income'&&tx.payment_status!=='paid'&&!tx.reversed_at)
 const payables=data.transactions.filter(tx=>tx.kind==='expense'&&tx.payment_status!=='paid'&&!tx.reversed_at)
 const collect=receivables.reduce((sum,tx)=>sum+transactionRemaining(tx),0)
 const pay=payables.reduce((sum,tx)=>sum+transactionRemaining(tx),0)
 return <div className="space-y-3 min-w-0">
  <div><h1 className="text-[17px] font-bold text-navy-900">Money map</h1><p className="text-[11.5px] text-navy-400">Where business money is, who holds it, and what is still due in or out.</p></div>
  <section className="rounded-2xl bg-navy-900 text-cream-50 p-3.5"><div className="text-[10px] font-bold uppercase tracking-wide text-cream-100/55">Business money we have</div><div className="num text-[27px] font-bold leading-tight mt-0.5">{businessMoney(total)}</div><div className="grid grid-cols-3 gap-1.5 mt-3"><Summary label="Shared / bank" value={shared.reduce((s,x)=>s+Number(x.balance),0)}/><Summary label="With partners" value={partnerHeld.reduce((s,x)=>s+Number(x.balance),0)}/><Summary label="With staff" value={staffHeld}/></div></section>
  <section className="grid grid-cols-2 gap-2"><DueCard to="/business/ledger" icon={ArrowDownLeft} label="To collect" value={collect} sub={receivables.length?receivables.length+' open customer amount'+(receivables.length===1?'':'s'):'Nothing pending'} tone="green"/><DueCard to="/business/ledger" icon={ArrowUpRight} label="To pay vendors" value={pay} sub={payables.length?payables.length+' open expense'+(payables.length===1?'':'s'):'Nothing pending'} tone="amber"/><DueCard to="/business/partners" icon={UserRound} label="We owe partners" value={partnerDue} sub="Personal spending / partner loans" tone="saffron"/><DueCard to="/business/staff" icon={UsersRound} label="We owe staff" value={staffDue} sub="Pocket expenses due back" tone="saffron"/></section>
  <section><div className="flex items-center justify-between mb-1.5"><h2 className="text-[13px] font-bold text-navy-900">Where business money is</h2><Link to="/business/accounts" className="text-[10.5px] font-semibold text-saffron-700">Manage</Link></div><div className="rounded-xl border border-cream-200 bg-white overflow-hidden">
   {active.map(balance=>{const account=data.accounts.find(a=>a.id===balance.account_id);if(!account)return null;const holder=account.custodian_partner_id?data.partners.find(p=>p.id===account.custodian_partner_id):null;return <div key={balance.account_id} className="min-h-[54px] px-3 py-2 flex items-center gap-2.5 border-b border-cream-100 last:border-0"><div className={'h-8 w-8 rounded-lg flex items-center justify-center shrink-0 '+(holder?'bg-saffron-50 text-saffron-700':'bg-navy-50 text-navy-600')}>{holder?<UserRound size={15}/>:account.kind==='bank'?<Building2 size={15}/>:<WalletCards size={15}/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5 min-w-0"><div className="text-[12px] font-semibold text-navy-800 truncate">{balance.name}</div>{holder&&<Badge tone="saffron">WITH {holder.name.toUpperCase()}</Badge>}</div><div className="text-[9.5px] text-navy-400 uppercase">{account.kind}</div></div><div className="num text-[13px] font-bold text-navy-900">{businessMoney(balance.balance)}</div></div>})}
   {data.staffPositions.filter(p=>Number(p.advance_balance)>0).map(p=><div key={'staff-'+p.staff_id} className="min-h-[54px] px-3 py-2 flex items-center gap-2.5 border-b border-cream-100 last:border-0"><div className="h-8 w-8 rounded-lg bg-saffron-50 text-saffron-700 flex items-center justify-center shrink-0"><UsersRound size={15}/></div><div className="min-w-0 flex-1"><div className="text-[12px] font-semibold text-navy-800 truncate">{p.name}</div><div className="text-[9.5px] text-navy-400">BUSINESS MONEY WITH STAFF</div></div><div className="num text-[13px] font-bold text-navy-900">{businessMoney(p.advance_balance)}</div></div>)}
  </div></section>
  {(partnerDue>0||staffDue>0)&&<section><h2 className="text-[13px] font-bold text-navy-900 mb-1.5">Personal money we owe back</h2><div className="rounded-xl border border-cream-200 bg-white overflow-hidden">{data.partnerPositions.filter(p=>Number(p.outstanding_due)>0).map(p=><OwedRow key={'p-'+p.partner_id} icon={UserRound} name={p.name} detail="Partner" amount={p.outstanding_due} to="/business/partners"/>)}{data.staffPositions.filter(p=>Number(p.outstanding_due)>0).map(p=><OwedRow key={'s-'+p.staff_id} icon={UsersRound} name={p.name} detail="Staff pocket expense" amount={p.outstanding_due} to="/business/staff"/>)}</div></section>}
  <div className="rounded-xl bg-cream-100 border border-cream-200 px-3 py-2.5 flex gap-2"><HandCoins size={16} className="text-saffron-700 shrink-0 mt-0.5"/><p className="text-[10.5px] leading-relaxed text-navy-500">Money shown under “with partner/staff” still belongs to the business. Amounts under “we owe” came from someone’s personal pocket or a partner loan.</p></div>
 </div>
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-white/10 border border-white/10 px-2 py-2"><div className="text-[8.5px] text-cream-100/50 font-semibold truncate">{label}</div><div className="num text-[11.5px] font-bold truncate">{businessMoney(value)}</div></div>}
function DueCard({to,icon:Icon,label,value,sub,tone}:{to:string;icon:typeof ArrowDownLeft;label:string;value:number;sub:string;tone:'green'|'amber'|'saffron'}){const cls=tone==='green'?'bg-green-50 border-green-100 text-paid':tone==='amber'?'bg-amber-50 border-amber-100 text-pend':'bg-saffron-50 border-saffron-200 text-saffron-700';return <Link to={to} className={'rounded-xl border p-2.5 min-w-0 active:scale-[0.99] '+cls}><div className="flex items-center justify-between gap-1"><span className="text-[9.5px] font-bold">{label}</span><Icon size={13}/></div><div className="num text-[15px] font-bold text-navy-900 mt-0.5">{businessMoney(value)}</div><div className="text-[9.5px] text-navy-400 leading-tight mt-0.5">{sub}</div></Link>}
function OwedRow({icon:Icon,name,detail,amount,to}:{icon:typeof UserRound;name:string;detail:string;amount:number;to:string}){return <Link to={to} className="min-h-[50px] px-3 py-2 flex items-center gap-2.5 border-b border-cream-100 last:border-0 active:bg-cream-50"><div className="h-8 w-8 rounded-lg bg-saffron-50 text-saffron-700 flex items-center justify-center"><Icon size={14}/></div><div className="min-w-0 flex-1"><div className="text-[11.5px] font-semibold text-navy-800 truncate">{name}</div><div className="text-[9.5px] text-navy-400">{detail}</div></div><div className="num text-[12px] font-bold text-pend">{businessMoney(amount)}</div><ArrowRight size={13} className="text-navy-300"/></Link>}
