import { useMemo, useState } from 'react'
import { CalendarClock, Play, Plus, Repeat2, Trash2 } from 'lucide-react'
import { Badge, Button, Field, Input, Modal, Select, Textarea } from '../../components/ui'
import { TypedConfirmModal } from '../../components/business/TypedConfirmModal'
import { useToast } from '../../components/Toast'
import { useBusiness } from '../../lib/business/store'
import { businessMoney, todayBusinessISO } from '../../lib/business/finance'
import type { BusinessPaidBy, BusinessRecurringEntry } from '../../lib/business/types'

type Form={kind:'income'|'expense';label:string;amount:string;accountId:string;partnerId:string;categoryId:string;counterparty:string;note:string;paidBy:BusinessPaidBy;cadence:'weekly'|'monthly';nextDate:string}

export default function BusinessRecurring(){
 const {data,canWrite,createRecurring,deleteRecurring,postRecurring}=useBusiness()
 const toast=useToast(),activeAccounts=data.accounts.filter(a=>a.active),activePartners=data.partners.filter(p=>p.active),today=todayBusinessISO()
 const defaultForm=():Form=>({kind:'expense',label:'',amount:'',accountId:activeAccounts[0]?.id??'',partnerId:activePartners[0]?.id??'',categoryId:'',counterparty:'',note:'',paidBy:'business',cadence:'monthly',nextDate:today})
 const [open,setOpen]=useState(false),[form,setForm]=useState<Form>(defaultForm),[busyId,setBusyId]=useState<string|null>(null),[deleting,setDeleting]=useState<BusinessRecurringEntry|null>(null)
 const entries=useMemo(()=>[...data.recurringEntries].sort((a,b)=>a.next_date.localeCompare(b.next_date)),[data.recurringEntries])
 const due=entries.filter(e=>e.active&&e.next_date<=today),upcoming=entries.filter(e=>e.active&&e.next_date>today)
 const openAdd=()=>{setForm(defaultForm());setOpen(true)}
 const save=async()=>{const amount=Number(form.amount);if(!canWrite||!form.label.trim()||amount<=0||!form.nextDate)return;if((form.kind==='income'||form.paidBy==='business')&&!form.accountId)return;if(form.kind==='expense'&&form.paidBy==='partner'&&!form.partnerId)return;setBusyId('create');try{await createRecurring({kind:form.kind,label:form.label,amount,accountId:form.kind==='income'||form.paidBy==='business'?form.accountId:null,partnerId:form.kind==='expense'&&form.paidBy==='partner'?form.partnerId:null,categoryId:form.categoryId||null,counterparty:form.counterparty,note:form.note,paidBy:form.paidBy,cadence:form.cadence,nextDate:form.nextDate});toast.success('Recurring entry saved');setOpen(false)}catch(error){toast.error(error instanceof Error?error.message:'Could not save recurring entry')}finally{setBusyId(null)}}
 const post=async(entry:BusinessRecurringEntry)=>{setBusyId(entry.id);try{await postRecurring(entry.id);toast.success(entry.kind==='income'?'Recurring receipt posted':'Recurring expense posted')}catch(error){toast.error(error instanceof Error?error.message:'Could not post recurring entry')}finally{setBusyId(null)}}
 const remove=async()=>{if(!deleting)return;setBusyId(deleting.id);try{await deleteRecurring(deleting.id);toast.success('Recurring entry deleted');setDeleting(null)}catch(error){toast.error(error instanceof Error?error.message:'Could not delete recurring entry')}finally{setBusyId(null)}}
 return <div className="space-y-3 min-w-0">
  <div className="flex items-start justify-between gap-2"><div><h1 className="text-[17px] font-bold text-navy-900">Regular payments</h1><p className="text-[11.5px] text-navy-400">Save money entries you repeat every week or month so you do not type them again.</p></div>{canWrite&&<button onClick={openAdd} className="h-9 px-3 shrink-0 rounded-xl bg-navy-900 text-white text-[11.5px] font-semibold flex items-center gap-1"><Plus size={14}/> Repeat</button>}</div>
  <div className="rounded-xl bg-navy-50 border border-navy-100 px-3 py-2 text-[11px] text-navy-600">Nothing moves automatically. When a saved entry is due, check it and tap <strong>Post now</strong>.</div>
  {due.length>0&&<section><div className="flex items-center justify-between mb-1.5"><h2 className="text-[13px] font-bold text-navy-900">Due now</h2><Badge tone="amber">{due.length}</Badge></div><div className="space-y-2">{due.map(e=><RecurringCard key={e.id} entry={e} data={data} busy={busyId===e.id} onPost={()=>void post(e)} onDelete={()=>setDeleting(e)}/>)}</div></section>}
  <section><h2 className="text-[13px] font-bold text-navy-900 mb-1.5">{due.length?'Coming next':'Saved regular entries'}</h2>{upcoming.length===0?<div className="rounded-xl border border-cream-200 bg-white px-4 py-7 text-center"><Repeat2 size={21} className="text-navy-300 mx-auto"/><div className="text-[12.5px] font-semibold text-navy-700 mt-1.5">No regular payments saved</div><div className="text-[10.5px] text-navy-400 mt-0.5">Save only payments or receipts you really repeat.</div></div>:<div className="space-y-2">{upcoming.map(e=><RecurringCard key={e.id} entry={e} data={data} busy={busyId===e.id} onPost={()=>void post(e)} onDelete={()=>setDeleting(e)}/>)}</div>}</section>
  <Modal open={open} onClose={()=>{if(!busyId)setOpen(false)}} title="Add regular payment" wide>
   <div className="grid grid-cols-2 gap-2"><Field label="Type"><Select value={form.kind} onChange={e=>setForm(v=>({...v,kind:e.target.value as Form['kind']}))}><option value="expense">Regular expense</option><option value="income">Regular money in</option></Select></Field><Field label="Amount"><Input inputMode="decimal" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))}/></Field></div>
   <Field label="Simple name" hint="Examples: Warehouse rent, Shopify subscription, Weekly collection."><Input value={form.label} onChange={e=>setForm(v=>({...v,label:e.target.value}))} autoFocus/></Field>
   {form.kind==='expense'&&<Field label="Usually paid by"><Select value={form.paidBy} onChange={e=>setForm(v=>({...v,paidBy:e.target.value as BusinessPaidBy}))}><option value="business">Business money</option><option value="partner">Partner personally</option></Select></Field>}
   {(form.kind==='income'||form.paidBy==='business')&&<Field label={form.kind==='income'?'Usually received into':'Usually paid from'}><Select value={form.accountId} onChange={e=>setForm(v=>({...v,accountId:e.target.value}))}><option value="">Choose money location</option>{activeAccounts.map(a=>{const h=a.custodian_partner_id?data.partners.find(p=>p.id===a.custodian_partner_id)?.name:null;return <option key={a.id} value={a.id}>{a.name}{h?' · with '+h:''}</option>})}</Select></Field>}
   {form.kind==='expense'&&form.paidBy==='partner'&&<Field label="Partner who usually pays personally"><Select value={form.partnerId} onChange={e=>setForm(v=>({...v,partnerId:e.target.value}))}><option value="">Choose partner</option>{activePartners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field>}
   <div className="grid grid-cols-2 gap-2"><Field label="Category"><Select value={form.categoryId} onChange={e=>setForm(v=>({...v,categoryId:e.target.value}))}><option value="">No category</option>{data.categories.filter(c=>c.active&&(form.kind==='income'?c.kind!=='expense':c.kind!=='income')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label={form.kind==='income'?'Customer / source':'Vendor / party'}><Input value={form.counterparty} onChange={e=>setForm(v=>({...v,counterparty:e.target.value}))}/></Field></div>
   <div className="grid grid-cols-2 gap-2"><Field label="Repeat"><Select value={form.cadence} onChange={e=>setForm(v=>({...v,cadence:e.target.value as Form['cadence']}))}><option value="weekly">Every week</option><option value="monthly">Every month</option></Select></Field><Field label="Next date"><Input type="date" value={form.nextDate} onChange={e=>setForm(v=>({...v,nextDate:e.target.value}))}/></Field></div>
   <Field label="Note"><Textarea value={form.note} onChange={e=>setForm(v=>({...v,note:e.target.value}))}/></Field><Button full loading={busyId==='create'} disabled={!form.label.trim()||Number(form.amount)<=0||!form.nextDate} onClick={save}>Save regular payment</Button>
  </Modal>
  <TypedConfirmModal open={!!deleting} mode="DELETE" title="Delete regular payment" body="This removes only this saved repeat. Money entries already posted from it stay in your history." busy={!!deleting&&busyId===deleting.id} onClose={()=>setDeleting(null)} onConfirm={remove}/>
 </div>
}
function RecurringCard({entry,data,busy,onPost,onDelete}:{entry:BusinessRecurringEntry;data:ReturnType<typeof useBusiness>['data'];busy:boolean;onPost:()=>void;onDelete:()=>void}){const due=entry.next_date<=todayBusinessISO(),account=data.accounts.find(a=>a.id===entry.account_id),partner=data.partners.find(p=>p.id===entry.partner_id),detail=entry.kind==='income'?account?.name||'Money in':entry.paid_by==='partner'?(partner?.name||'Partner')+' personally':account?.name||'Business money';return <div className={'rounded-xl border bg-white p-3 '+(due?'border-amber-200':'border-cream-200')}><div className="flex items-start gap-2.5"><div className={'h-9 w-9 rounded-lg flex items-center justify-center shrink-0 '+(due?'bg-amber-50 text-pend':'bg-navy-50 text-navy-600')}><CalendarClock size={16}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><div className="text-[12.5px] font-bold text-navy-900 truncate">{entry.label}</div>{due&&<Badge tone="amber">DUE</Badge>}</div><div className="text-[10px] text-navy-400 truncate">{entry.cadence==='weekly'?'Weekly':'Monthly'} · {detail} · next {new Date(entry.next_date+'T00:00:00').toLocaleDateString('en-IN')}</div></div><div className="num text-[14px] font-bold text-navy-900">{businessMoney(entry.amount)}</div></div><div className="grid grid-cols-[1fr_42px] gap-2 mt-2"><Button variant={due?'accent':'soft'} className="!min-h-[36px] !text-[11px]" loading={busy} onClick={onPost}><Play size={13}/> Post now</Button><Button variant="danger" className="!min-h-[36px] !px-0" aria-label={'Delete '+entry.label} onClick={onDelete}><Trash2 size={13}/></Button></div></div>}
